In [7]:
import numpy as np
inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
targets = np.array([
    [0],
    [1],
    [1],
    [0]
])

In [8]:
np.random.seed(0)
weights_input_hidden = np.random.uniform(size=(2, 2))
bias_hidden = np.random.uniform(size=(1, 2))
weights_hidden_output = np.random.uniform(size=(2, 1))
bias_output = np.random.uniform(size=(1, 1))

In [9]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [10]:
learning_rate = 0.1
epochs = 10000

In [11]:
for _ in range(epochs):

    hidden_layer_input = np.dot(inputs, weights_input_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
    predicted_output = sigmoid(output_layer_input)

    error = targets - predicted_output

    d_output = error * sigmoid_derivative(predicted_output)
    d_hidden = np.dot(d_output, weights_hidden_output.T) * sigmoid_derivative(hidden_layer_output)

    weights_hidden_output += np.dot(hidden_layer_output.T, d_output) * learning_rate
    bias_output += np.sum(d_output, axis=0, keepdims=True) * learning_rate
    weights_input_hidden += np.dot(inputs.T, d_hidden) * learning_rate
    bias_hidden += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

In [12]:
print("\nPredicted XOR outputs (after training):")
print(np.round(predicted_output))


Predicted XOR outputs (after training):
[[0.]
 [1.]
 [1.]
 [0.]]


In [13]:
print("\nFinal Weights and Biases:")
print("Input-Hidden Weights:\n", weights_input_hidden)
print("Hidden Bias:\n", bias_hidden)
print("Hidden-Output Weights:\n", weights_hidden_output)
print("Output Bias:\n", bias_output)


Final Weights and Biases:
Input-Hidden Weights:
 [[3.70986741 5.78826314]
 [3.71149043 5.79621929]]
Hidden Bias:
 [[-5.6837777  -2.42016264]]
Hidden-Output Weights:
 [[-8.14923676]
 [ 7.50521163]]
Output Bias:
 [[-3.37826206]]
